name: Deploy to Vercel
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          preserve-timestamps: true

      - name: Setup Git and Debug Info
        run: |
          git config --global core.quotepath false
          git config --global --add safe.directory '*'
          echo "Git version: $(git --version)"
          echo "Current branch: $(git branch --show-current)"
          echo "Last commit: $(git log -1 --pretty=format:'%h - %s (%ad)' --date=iso)"
          echo "Sample file dates:"
          git ls-tree -r --full-name --full-tree HEAD src/posts | while read -r mode type hash file; do
            echo "$file: $(git log -1 --format=%ai -- "$file")"
          done

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Set timezone
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "Current time: $(date)"

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deployment Status
        run: |
          echo "Deployment completed at $(date)"
          echo "Timezone: $(cat /etc/timezone)"
