name: Deploy to Vercel
on:
  push:
    branches: [master] # 根据你的主分支名称调整

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整的 git 历史
          preserve-timestamps: true # 保留文件时间戳

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # 根据你的 Node.js 版本调整
          cache: "npm" # 或 'yarn' 如果你使用 yarn

      - name: Install dependencies
        run: npm ci # 或 'yarn install --frozen-lockfile'

      - name: Set timezone
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "Current time: $(date)"

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
